changelogs:
  - changelog: ChangeLog.md

    ignore_files:
      - "*ChangeLog*.md"
      - .changelogged.yaml

    ignore_commits: []

    version_files:
      - path: package.yaml
        version_pattern:
          variable: "version"
          separator: ":"
      - path: src/Changelogged/Common/Utils/Pure.hs
        version_pattern:
          variable: "changeloggedVersion"
          separator: "="

branch: origin/master

entry_format: "  - %message% (see [%link%](%id%));"

editor_command: "nano -EiT 2"
