changelogs:
  - changelog: ChangeLog.md

    level_headers:
      major: "* Major"
      minor: "* Minor"
      fix: "* Fix"
      doc: "* Doc"

    ignore_files:
      - ChangeLog.md

    version_files:
      - path: package.yaml
        version_pattern: "version:"
      - path: src/Changelogged/Pure.hs
        version_pattern: "changeloggedVersion ="
