changelogs:
  - changelog: ChangeLog.md

    level_headers:
      major: "* Major"
      minor: "* Minor"
      fix: "* Fix"
      doc: "* Doc"

    ignore_files:
      - ChangeLog.md
      - .changelogged.yaml

    ignore_commits:
      - Update ChangeLog and bump versions
      - Update ChangeLog.md and bump versions
      - Bump versions

    version_files:
      - path: package.yaml
        version_pattern:
          variable: "version"
          separator: ":"
      - path: src/Changelogged/Common/Utils/Pure.hs
        version_pattern:
          variable: "changeloggedVersion"
          separator: "="

branch: origin/master

entry_format: "  - %message% (see [%link%](%id%));"

editor_command: "nano -EiT 2"
