changelogs:
  - changelog: ChangeLog.md

    ignore_files:
      - ChangeLog.md

    version_files:
      - path: package.yaml
        version_pattern: "version:"
      - path: src/Changelogged/Pure.hs
        version_pattern: "changeloggedVersion ="
    
    default: true
