# Template configuration file for changelogged - Changelog Manager for Git Projects
# See documentation at https://github.com/GetShopTV/changelogged#readme
changelogs:
  # package changelog (for library and executables)
  - changelog: ChangeLog.md

    ignore_files:
      # Ignore ChangeLog itself.
      - ChangeLog.md
      # Ignore package.yaml files in root and any subdirectory.
      - "**package.yaml"
      # Ignore LICENSE files on the first tier of file tree and deeper.
      - "*/**LICENSE"
      # Ignore all .md files on the first tier and deeper.
      - "*/**md"
    
    # which individual changes to ignore
    #
    # ignore_commits: []

    # which files to modify when performing a regular version bump
    version_files:
      # for hpack-enabled Haskell projects
      # version in package.yaml should be updated
      - path: package.yaml
        version_pattern:
          variable: "version"
          separator: ":"

  # HTTP API changelog
  - changelog: API_ChangeLog.md

    # only watch changes to swagger.json file
    watch_files:
      - swagger.json

    # which files to modify when performing
    # an API version bump
    version_files:
      # version should be changed in Haskell module
      # that specifies version for a generated swagger.json
      - path: 'src/MyProject/API/Version.hs'
        version_pattern:
          variable: 'apiVersion'
          separator: '='

      # swagger.json should also be updated
      - path: 'swagger.json'
        version_pattern:
          variable: '"version"'
          separator: ':'
        
# Branch with version tags
# for projects following Git Flow this should be master,
# since development and feature branches might not have version tags
#
# branch: master

# Format of entries going to be added to changelogs
# entry_format: "  - %message% (see [%link%](%id%));"

# Text editor command to run for editing changelog.
# editor_command: "nano -i"
