changelogs:
  - changelog: ChangeLog.md

    level_headers:
      major: "* Major"
      minor: "* Minor"
      fix: "* Fix"
      doc: "* Doc"

    ignore_files:
      - ChangeLog.md
      - .changelogged.yaml

    ignore_commits: []

    version_files:
      - path: package.yaml
        version_pattern:
          variable: "version"
          separator: ":"
      - path: src/Changelogged/Pure.hs
        version_pattern:
          variable: "changeloggedVersion"
          separator: "="
