name: changelogged
version: 0.3.0
synopsis: Changelog manager for Git projects.
description: Please see the README on Github at <https://github.com/GetShopTV/changelogged#readme>
maintainer: Vitalii Guzeev <vitaliy@getshoptv.com>
copyright: (c) 2017-2018, GetShop.TV
license: BSD3
license-file: LICENSE
author: Vitalii Guzeev <vitaliy@getshoptv.com>
github: GetShopTV/changelogged
category: Development
extra-source-files:
  - README.md
  - ChangeLog.md
  - images/*

custom-setup:
  dependencies:
  - base
  - Cabal
  - cabal-doctest >=1.0.2 && <1.1

dependencies:
  - base >= 4.7 && < 5
  - turtle >= 1.5.0
  - text
  - unordered-containers
  - ansi-terminal

library:
  source-dirs: src
  dependencies:
    - optparse-applicative
    - process
    - yaml
    - aeson
    - mtl
    - transformers-base
    - exceptions
    - system-filepath
    - string-conversions
    - foldl
    - vector
    - either

executables:
  changelogged:
    source-dirs:      app
    main:             Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - changelogged

tests:
  doctests:
    source-dirs: test
    main: doctests.hs
    other-modules: []
    dependencies:
    - base
    - doctest
    - Glob
    - QuickCheck
